spring.application.name=said-urban-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/db_said_urban
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Tamaño máximo de archivos (para la foto del INE)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB